### PR TITLE
fix(66): Let user pass the initial state as a function.

### LINKED ISSUE #66: Nested store objects not being reset to it's initial state
When using nested objects as part of your store, calling `store.reset()` will not reset the nested objects to their respective initial state values.

e.g.
```TypeScript
interface SomeStore {
  test1: {
    value: boolean;
  },
  test2: boolean;
}

const store = createStore<SomeStore>({
  test1: {
    value: false,
  },
  test2: false
});

```

### PR DESCRIPTION
**Pull request by Serabe**
Some users are using stencil-store with deep objects. This is a way
for reset to keep working for them.

Closes #66

### CODE REVIEW

**Comment by Serabe** [comment]
@splitinfinities any updates on this?

**Comment by splitinfinities** [comment]
Hey folks! Unfortunately I've moved on from Stencil, so ping the Stencil team on their progress.

**Comment by wvduijn82** [comment]
@manucorporat any update on this? Review is open for quite some time now. And this would be a very nice addition to the store

**Comment by rwaskiewicz** [comment]
@Serabe Can do. I'll circle back around to this early next week to take a first pass at it

**Comment by rwaskiewicz** [comment]
This seems reasonable to me at a first glance.

I want to cut a release of this library with a new minimum `peer-dependencies` value of `@stencil/core: >=2.0.0` (which will be a breaking change + require a major version bump of this library), and I'll circle back to do a more formal review.  This is still very much on my radar/plan to get a more thorough review done early this week.

**Comment by Serabe** [comment]
Is there any reason to require a newer version of Stencil? This change has been waiting review for months and does work with older versions.

**Comment by rwaskiewicz** [comment]
> Is there any reason to require a newer version of Stencil? This change has been waiting review for months and does work with older versions.

The Stencil team [doesn't support Stencil v1](https://stenciljs.com/docs/support-policy), which is the reason behind the newer version requirement.  Specifically, I'd like us to be releasing versions of these types of libraries (i.e. stencil-store) where the project's peer-dependencies aligns with our support policy moving forward

**Comment by rwaskiewicz** [comment]
> I can understand that but is there any reason to do that before releasing this feature?

My thought process here is that releasing this feature without bumping the peer dependency on stencil core to v2+ first is that we're implying support for this feature with stencil v1, which the team can't guarantee at this time (since we don't support that major version of stencil)

**Review by rwaskiewicz — CHANGES_REQUESTED** [review]
Thanks @Serabe! Tested locally, everything seems to be working as intended 👍 

I had a few minor comments, none of which are directly related to the code itself.  Would you mind addressing these?

**Comment by Serabe** [comment]
@rwaskiewicz done!

**Pull request merged**
